### ISSUE TITLE
No OxfordDictionaries.py in OxfordAPI

### ISSUE THREAD

**Issue by dipendrayadaveee** [RafaelBroseghini/OxfordAPI#2]
Hi Rafael,
Thank you for creating this python wrapper around the Oxford Dictionary API.
As, you have mentioned in the installation steps that we need to run:
`python OxfordDictionaries.py` but there is no OxfordDictionaries.py in the folder.
Can you please suggest a solution to it?
Thanks.

**Comment by Jakub-Golinowski** [comment]
You can create this file manually using the code in readme: 
```
from oxforddictionaries.words import OxfordDictionaries

o = OxfordDictionaries(app_id, app_key)

relax = o.get_synonyms("absorb").json()

synonyms = relax['results'][0]['lexicalEntries'][0]['entries'][0]['senses'][0]['synonyms']

for s in range(10):
    print(synonyms[s]['text'])
```

Also, if you are interested in API v2, you can take a look at my fork: https://github.com/Jakub-Golinowski/OxfordAPI/tree/api_v2
